### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Renkoto** [guihkx/Installer#1]
This looks a bit abandoned, but still worth reporting.

**Describe the bug**
Install/repair failed

**To Reproduce**
1. Run ```BetterDiscord 1.0.0```
2. Select Repair or Install Betterdiscord
3. Select Discord

**What should happen:**
It should install.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/69415770/125856110-f48060f7-0341-48ed-954c-962f1383dd7c.png)

**System Information:**
 - OS: [Manjaro]
- Discord Version: [Stable]

**Additional context**
This issue was already fixed in the main installer.

**Comment by guihkx** [comment]
Thanks for reporting! Should be fixed in latest release.
