### ISSUE TITLE
Update to BetterDiscord v1.9.4

### ISSUE THREAD

**Issue by azzamsa** [guihkx/Installer#2]
Hi.

Would you like to update to `BetterDiscord v1.9.4`?

Thanks for this fork! 🏅

**Comment by guihkx** [comment]
Hey,

I'm not sure I understand. Is the installer not downloading v1.9.4 for you? It is for me:

![image](https://github.com/guihkx/Installer/assets/626206/0979628c-fa0e-4ed6-a71d-0f69527387c9)

**Comment by azzamsa** [comment]
Oh, thank you.

I mistook the installer must always be the same version as the core.
